[2024-06-06T18:34:08.974+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T18:34:08.990+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.extract_weather_data manual__2024-06-06T18:34:01.417648+00:00 [queued]>
[2024-06-06T18:34:08.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.extract_weather_data manual__2024-06-06T18:34:01.417648+00:00 [queued]>
[2024-06-06T18:34:08.998+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-06T18:34:09.009+0000] {taskinstance.py:2330} INFO - Executing <Task(SimpleHttpOperator): extract_weather_data> on 2024-06-06 18:34:01.417648+00:00
[2024-06-06T18:34:09.015+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2370) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-06T18:34:09.016+0000] {standard_task_runner.py:63} INFO - Started process 2372 to run task
[2024-06-06T18:34:09.016+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'extract_weather_data', 'manual__2024-06-06T18:34:01.417648+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp9b7ddk0l']
[2024-06-06T18:34:09.017+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask extract_weather_data
[2024-06-06T18:34:09.053+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.extract_weather_data manual__2024-06-06T18:34:01.417648+00:00 [running]> on host 918bc5ab046e
[2024-06-06T18:34:09.113+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='eajavon08@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T18:34:01.417648+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T18:34:01.417648+00:00'
[2024-06-06T18:34:09.114+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T18:34:09.115+0000] {http.py:169} INFO - Calling HTTP method
[2024-06-06T18:34:09.122+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-06-06T18:34:09.128+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-06-06T18:34:09.924+0000] {http.py:208} INFO - {"coord":{"lon":-122.6762,"lat":45.5234},"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"base":"stations","main":{"temp":294.25,"feels_like":293.85,"temp_min":292.11,"temp_max":297.03,"pressure":1018,"humidity":55},"visibility":10000,"wind":{"speed":3.09,"deg":0},"clouds":{"all":20},"dt":1717698848,"sys":{"type":2,"id":2008548,"country":"US","sunrise":1717676575,"sunset":1717732583},"timezone":-25200,"id":5746545,"name":"Portland","cod":200}
[2024-06-06T18:34:09.926+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T18:34:09.927+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 166, in execute
    return self.execute_sync(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 172, in execute_sync
    return self.process_response(context=context, response=response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 215, in process_response
    return self.response_filter(response, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag.py", line 83, in <lambda>
    response_filter = lambda r: json.load(r.text),
                                ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^
AttributeError: 'str' object has no attribute 'read'
[2024-06-06T18:34:09.941+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=extract_weather_data, run_id=manual__2024-06-06T18:34:01.417648+00:00, execution_date=20240606T183401, start_date=20240606T183408, end_date=20240606T183409
[2024-06-06T18:34:09.955+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task extract_weather_data ('str' object has no attribute 'read'; 2372)
[2024-06-06T18:34:09.996+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T18:34:10.005+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
  result = cls.__new__(cls)

[2024-06-06T18:34:10.015+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T18:34:10.017+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
