[2024-06-06T18:49:59.830+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T18:49:59.850+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.extract_weather_data manual__2024-06-06T18:45:47.720703+00:00 [queued]>
[2024-06-06T18:49:59.859+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.extract_weather_data manual__2024-06-06T18:45:47.720703+00:00 [queued]>
[2024-06-06T18:49:59.860+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-06-06T18:49:59.870+0000] {taskinstance.py:2330} INFO - Executing <Task(SimpleHttpOperator): extract_weather_data> on 2024-06-06 18:45:47.720703+00:00
[2024-06-06T18:49:59.877+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2593) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-06T18:49:59.879+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'extract_weather_data', 'manual__2024-06-06T18:45:47.720703+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpwbf4h7ik']
[2024-06-06T18:49:59.881+0000] {standard_task_runner.py:63} INFO - Started process 2595 to run task
[2024-06-06T18:49:59.881+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask extract_weather_data
[2024-06-06T18:49:59.928+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.extract_weather_data manual__2024-06-06T18:45:47.720703+00:00 [running]> on host 918bc5ab046e
[2024-06-06T18:50:00.000+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='eajavon08@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T18:45:47.720703+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T18:45:47.720703+00:00'
[2024-06-06T18:50:00.001+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T18:50:00.002+0000] {http.py:169} INFO - Calling HTTP method
[2024-06-06T18:50:00.014+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-06-06T18:50:00.023+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-06-06T18:50:07.306+0000] {http.py:208} INFO - {"coord":{"lon":-122.6762,"lat":45.5234},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"base":"stations","main":{"temp":294.71,"feels_like":294.33,"temp_min":292.25,"temp_max":297.59,"pressure":1018,"humidity":54},"visibility":10000,"wind":{"speed":1.79,"deg":229,"gust":4.02},"clouds":{"all":5},"dt":1717699678,"sys":{"type":2,"id":2008548,"country":"US","sunrise":1717676575,"sunset":1717732583},"timezone":-25200,"id":5746545,"name":"Portland","cod":200}
[2024-06-06T18:50:07.307+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T18:50:07.309+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 166, in execute
    return self.execute_sync(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 172, in execute_sync
    return self.process_response(context=context, response=response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 215, in process_response
    return self.response_filter(response, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag.py", line 84, in <lambda>
    response_filter = lambda r: json.load(r.text),
                                ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^
AttributeError: 'str' object has no attribute 'read'
[2024-06-06T18:50:07.328+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=extract_weather_data, run_id=manual__2024-06-06T18:45:47.720703+00:00, execution_date=20240606T184547, start_date=20240606T184959, end_date=20240606T185007
[2024-06-06T18:50:07.344+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task extract_weather_data ('str' object has no attribute 'read'; 2595)
[2024-06-06T18:50:07.386+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T18:50:07.397+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
  result = cls.__new__(cls)

[2024-06-06T18:50:07.407+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T18:50:07.410+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
